all:
	g++ -g -std=c++11 -Wall -I../libs/ -o message-sender message-sender.cpp -L../libs/libboost -lboost_system -lboost_chrono -lboost_random -lboost_thread -lpthread -ldl -Wl,-rpath=../libs/libboost/
